# Generated by Django 5.0.3 on 2024-04-12 11:21

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('postobjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
